### ISSUE TITLE
SyntaxError

### ISSUE THREAD

**Issue by rocketkoll** [termux-lab/sherlock#2]
File "/data/data/com.termux/files/home/sherlock/sherl.py", line 4

    ^
SyntaxError: invalid syntax

**Comment by antohin91** [comment]
I have the same

**Comment by gh-cmd** [comment]
Did you find the answer?

**Comment by rocketkoll** [comment]
No..

**Comment by reallydoc** [comment]
https://github.com/termux-lab/sherlock/issues/2#issue-733550592 - this is my problem too(

**Comment by Andscral** [comment]
Has anyone found a solution to the syntax problem?

**Comment by climbet** [comment]
> Has anyone found a solution to the syntax problem?

Yeap

**Comment by Andscral** [comment]
> > Кто-нибудь нашел решение проблемы синтаксиса?
> 
> Да

Can you please tell me?

**Comment by Insta177** [comment]
> > Кто-нибудь нашел решение проблемы синтаксиса?
> 
> Да



> > Has anyone found a solution to the syntax problem?
> 
> Yeap

Please help

**Comment by Insta177** [comment]
> > Has anyone found a solution to the syntax problem?
> 
> Yeap

Please help

**Comment by PVkolos** [comment]
> > Кто-нибудь нашел решение проблемы синтаксиса?
> 
> Да

Help, please

**Comment by PVkolos** [comment]
> > > Has anyone found a solution to the syntax problem?
> > 
> > 
> > Yeap
> 
> Please help

We anyone found a solution to the syntax problem?

**Comment by pavel901** [comment]
И у меня проблема такаежа что делать?

**Comment by vladoss-huila** [comment]
Как теперь удалить эту прогу?

**Comment by LostHackerInThisWorld** [comment]
Эм... Я вам не мешаю? Код как-бы зашифрован, пофиксить нельзя.

**Comment by Boom-jack** [comment]
И все же как убрать данную ошибку?

**Comment by FlingerXD** [comment]
> Эм... Я вам не мешаю? Код как-бы зашифрован, пофиксить нельзя.

У меня раньше работало, щас установил и ошибка синтаксиса

**Comment by Namig09** [comment]
> Как теперь удалить эту прогу?

rm -rf name

**Comment by termux-lab** [comment]
Начал работать над ним, скоро будет работать

**Comment by termux-lab** [comment]
Исправлено
